// <auto-generated />
namespace Seminarski.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TestniSeminarPopulateData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestniSeminarPopulateData));
        
        string IMigrationMetadata.Id
        {
            get { return "202005250512028_TestniSeminarPopulateData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
